import React,{useEffect,useState}from'react';
import{SafeAreaView,View,Text,TouchableOpacity,StyleSheet,ScrollView,RefreshControl,StatusBar,Alert,Linking,ActivityIndicator}from'react-native';
import{Image}from'expo-image';
import{installBundledOrRemoteCache,GTA_DIR}from'./cacheService';
import{prepareClient}from'./clientService';
const SERVER={name:'MYTHØS RP',host:'51.68.107.75',port:10961,maxPlayers:500,mode:'ROLEPLAY'};
const CLIENT_SCHEME='samp';
export default function App(){
 const[refreshing,setRefreshing]=useState(false),[cacheBusy,setCacheBusy]=useState(true),[cacheReady,setCacheReady]=useState(false),[clientBusy,setClientBusy]=useState(true),[clientReady,setClientReady]=useState(false),[clientVersion,setClientVersion]=useState(null);
 const checkServer=async()=>{setRefreshing(true);try{await fetch('https://clients3.google.com/generate_204',{method:'GET',cache:'no-store'});}catch{}finally{setRefreshing(false)}};
 const prepareCache=async()=>{setCacheBusy(true);try{const result=await installBundledOrRemoteCache();setCacheReady(true);if(result.installed)Alert.alert('MYTHØS Launcher','Cache do GTA preparado automaticamente.');}catch(e){setCacheReady(false);Alert.alert('Cache do GTA','Não foi possível preparar o cache automaticamente.\n\n'+String(e?.message||e));}finally{setCacheBusy(false)}};
 const prepareClientAutomatic=async()=>{setClientBusy(true);try{const manifest=await prepareClient();setClientVersion(manifest?.version||null);setClientReady(true);}catch(e){setClientReady(false);Alert.alert('Cliente MYTHØS','Não foi possível baixar o cliente automaticamente.\n\n'+String(e?.message||e));}finally{setClientBusy(false)}};
 const prepareAll=async()=>{await checkServer();await Promise.allSettled([prepareCache(),prepareClientAutomatic()])};
 const play=async()=>{try{if(cacheBusy||clientBusy){Alert.alert('MYTHØS Launcher','Aguarde o download automático terminar.');return}if(!cacheReady||!clientReady){Alert.alert('MYTHØS Launcher','O jogo ainda não está pronto.');return}const uri=`${CLIENT_SCHEME}://${SERVER.host}:${SERVER.port}`;if(await Linking.canOpenURL(uri)){await Linking.openURL(uri);return}Alert.alert('MYTHØS Launcher','O cliente MYTHØS SA-MP Mobile ainda não está disponível no Android.');}catch{Alert.alert('Falha','Não foi possível abrir o cliente SA-MP.')}};
 useEffect(()=>{prepareAll()},[]);
 return <SafeAreaView style={s.root}><StatusBar barStyle="light-content"/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={prepareAll}/>} contentContainerStyle={s.content}>
  <View style={s.header}><Image source={require('./assets/logo.jpg')} style={s.logo} contentFit="contain"/><Text style={s.network}>MYTHØS NETWORK</Text><Text style={s.title}>MYTHØS LAUNCHER</Text><Text style={s.subtitle}>MYTHØS RP • SA-MP MOBILE</Text><View style={s.status}><View style={s.dot}/><Text style={s.statusText}>{cacheBusy||clientBusy?'BAIXANDO E PREPARANDO':'PRONTO PARA JOGAR'}</Text></View></View>
  <View style={s.card}><Text style={s.kicker}>SERVIDOR PRINCIPAL</Text><Text style={s.serverName}>{SERVER.name}</Text><Text style={s.meta}>{SERVER.host}:{SERVER.port} • {SERVER.mode}</Text><View style={s.stats}><View><Text style={s.number}>{SERVER.port}</Text><Text style={s.small}>PORTA</Text></View><View><Text style={s.number}>500</Text><Text style={s.small}>SLOTS</Text></View><View><Text style={s.number}>2.11</Text><Text style={s.small}>CLIENTE</Text></View></View><TouchableOpacity style={[s.play,(cacheBusy||clientBusy||!cacheReady||!clientReady)&&s.playDisabled]} onPress={play} disabled={cacheBusy||clientBusy||!cacheReady||!clientReady}><Text style={s.playText}>{cacheBusy||clientBusy?'BAIXANDO...':'▶  JOGAR AGORA'}</Text></TouchableOpacity></View>
  <Text style={s.section}>INSTALAÇÃO AUTOMÁTICA</Text><View style={s.item}><View style={s.icon}><Text style={s.iconText}>M</Text></View><View style={s.info}><Text style={s.itemTitle}>GTA + Cache MYTHØS</Text><Text style={s.itemMeta}>{cacheBusy?'Baixando e preparando automaticamente...':cacheReady?'Pronto em '+GTA_DIR:'Falha na preparação'}</Text></View>{cacheBusy?<ActivityIndicator size="small" color="#ff334f"/>:cacheReady?<Text style={s.ok}>✓</Text>:<Text style={s.fail}>!</Text>}</View>
  <View style={s.item}><View style={s.icon}><Text style={s.iconText}>S</Text></View><View style={s.info}><Text style={s.itemTitle}>MYTHØS SA-MP Mobile</Text><Text style={s.itemMeta}>{clientBusy?'Baixando automaticamente...':clientReady?`Cliente ${clientVersion||'2.11'} pronto`:'Falha no download'}</Text></View>{clientBusy?<ActivityIndicator size="small" color="#ff334f"/>:clientReady?<Text style={s.ok}>✓</Text>:<Text style={s.fail}>!</Text>}</View><Text style={s.help}>O launcher baixa e prepara o cliente automaticamente. Não existe botão separado para o cliente.</Text>
  <Text style={s.footer}>MYTHØS LAUNCHER • MYTHØS NETWORK • {SERVER.host}:{SERVER.port}</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050505'},content:{paddingBottom:35},header:{padding:20,alignItems:'center'},logo:{width:'100%',height:155},network:{color:'#888',fontSize:10,fontWeight:'900',letterSpacing:3},title:{color:'#fff',fontSize:31,fontWeight:'900',letterSpacing:2,marginTop:5},subtitle:{color:'#ff334f',fontSize:10,fontWeight:'800',letterSpacing:2,marginTop:4},status:{marginTop:14,flexDirection:'row',alignItems:'center',backgroundColor:'#111',borderRadius:20,paddingHorizontal:12,paddingVertical:7,borderWidth:1,borderColor:'#302025'},dot:{width:7,height:7,borderRadius:4,marginRight:7,backgroundColor:'#31d17c'},statusText:{color:'#ddd',fontSize:10,fontWeight:'900',letterSpacing:1},card:{margin:18,padding:21,borderRadius:21,backgroundColor:'#111',borderWidth:1,borderColor:'#4a2027'},kicker:{color:'#ff334f',fontSize:10,fontWeight:'900',letterSpacing:2},serverName:{color:'#fff',fontSize:25,fontWeight:'900',marginTop:8},meta:{color:'#818181',fontSize:11,marginTop:4},stats:{flexDirection:'row',justifyContent:'space-between',marginTop:22},number:{color:'#fff',fontSize:21,fontWeight:'900'},small:{color:'#777',fontSize:8,fontWeight:'900',marginTop:3},play:{marginTop:24,backgroundColor:'#ff334f',borderRadius:13,padding:16,alignItems:'center'},playDisabled:{backgroundColor:'#3a171c'},playText:{color:'#fff',fontSize:12,fontWeight:'900',letterSpacing:1},section:{marginHorizontal:22,marginTop:24,marginBottom:10,color:'#777',fontSize:10,fontWeight:'900',letterSpacing:2},item:{marginHorizontal:18,marginTop:8,padding:15,borderRadius:15,backgroundColor:'#0f0f0f',borderWidth:1,borderColor:'#282020',flexDirection:'row',alignItems:'center'},icon:{width:44,height:44,borderRadius:12,backgroundColor:'#ff334f',alignItems:'center',justifyContent:'center'},iconText:{color:'#fff',fontWeight:'900',fontSize:19},info:{flex:1,marginLeft:12},itemTitle:{color:'#fff',fontSize:13,fontWeight:'900'},itemMeta:{color:'#737373',fontSize:9,marginTop:4},ok:{color:'#31d17c',fontSize:20,fontWeight:'900'},fail:{color:'#ff334f',fontSize:18,fontWeight:'900'},help:{marginHorizontal:22,marginTop:10,color:'#555',fontSize:9,lineHeight:14},footer:{textAlign:'center',color:'#555',fontSize:9,marginTop:30}});
