import React,{useEffect,useState}from'react';
import{SafeAreaView,View,Text,TouchableOpacity,StyleSheet,ScrollView,RefreshControl,StatusBar,Alert,Linking,ActivityIndicator}from'react-native';
import{Image}from'expo-image';
import{installBundledOrRemoteCache,GTA_DIR}from'./cacheService';
import{prepareClient}from'./clientService';

const SERVER={name:'MYTHØS RP',host:'51.68.107.75',port:10961,maxPlayers:500,mode:'ROLEPLAY'};
const CLIENT_SCHEME='samp';
export default function App(){
 const[refreshing,setRefreshing]=useState(false),[cacheBusy,setCacheBusy]=useState(true),[cacheReady,setCacheReady]=useState(false),[clientBusy,setClientBusy]=useState(false),[clientVersion,setClientVersion]=useState(null);
 const checkServer=async()=>{setRefreshing(true);try{await fetch('https://clients3.google.com/generate_204',{method:'GET',cache:'no-store'});}catch{}finally{setRefreshing(false)}};
 const prepareCache=async()=>{setCacheBusy(true);try{const result=await installBundledOrRemoteCache();setCacheReady(true);if(result.installed)Alert.alert('MYTHØS Launcher','Cache do GTA preparado automaticamente.');}catch(e){setCacheReady(false);Alert.alert('Cache do GTA','Não foi possível preparar o cache automaticamente. Verifique a internet e tente novamente.\n\n'+String(e?.message||e));}finally{setCacheBusy(false)}};
 const installClient=async()=>{setClientBusy(true);try{const manifest=await prepareClient();setClientVersion(manifest?.version||null);Alert.alert('Cliente pronto','O instalador do Android foi aberto para concluir a instalação do MYTHØS SA-MP Mobile.');}catch(e){Alert.alert('Erro ao preparar cliente','Não foi possível baixar/instalar o cliente agora.\n\n'+String(e?.message||e));}finally{setClientBusy(false)}};
 const play=async()=>{try{if(!cacheReady){await prepareCache();return}const uri=`${CLIENT_SCHEME}://${SERVER.host}:${SERVER.port}`;if(await Linking.canOpenURL(uri)){await Linking.openURL(uri);return}Alert.alert('Cliente MYTHØS','Instale o cliente MYTHØS SA-MP Mobile primeiro e tente novamente.');}catch{Alert.alert('Falha','Não foi possível abrir o cliente SA-MP.')}};
 useEffect(()=>{checkServer();prepareCache()},[]);
 return <SafeAreaView style={s.root}><StatusBar barStyle="light-content"/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{checkServer();prepareCache()}}/>} contentContainerStyle={s.content}>
  <View style={s.header}><Image source={require('./assets/logo.jpg')} style={s.logo} contentFit="contain"/><Text style={s.network}>MYTHØS NETWORK</Text><Text style={s.title}>MYTHØS LAUNCHER</Text><Text style={s.subtitle}>MYTHØS RP • SA-MP MOBILE</Text><View style={s.status}><View style={s.dot}/><Text style={s.statusText}>{cacheBusy?'PREPARANDO O JOGO':'PRONTO PARA CONECTAR'}</Text></View></View>
  <View style={s.card}><Text style={s.kicker}>SERVIDOR PRINCIPAL</Text><Text style={s.serverName}>{SERVER.name}</Text><Text style={s.meta}>{SERVER.host}:{SERVER.port} • {SERVER.mode}</Text><View style={s.stats}><View><Text style={s.number}>{SERVER.port}</Text><Text style={s.small}>PORTA</Text></View><View><Text style={s.number}>500</Text><Text style={s.small}>SLOTS</Text></View><View><Text style={s.number}>2.11</Text><Text style={s.small}>CLIENTE</Text></View></View><TouchableOpacity style={s.play} onPress={play} disabled={cacheBusy}><Text style={s.playText}>{cacheBusy?'PREPARANDO...':'▶  ENTRAR NO SERVIDOR'}</Text></TouchableOpacity></View>
  <Text style={s.section}>JOGO</Text><View style={s.cache}><View style={s.cacheIcon}><Text style={s.cacheIconText}>M</Text></View><View style={s.cacheInfo}><Text style={s.itemTitle}>GTA + Cache MYTHØS</Text><Text style={s.itemMeta}>{cacheBusy?'Baixando e preparando automaticamente...':cacheReady?'Pronto em '+GTA_DIR:'Aguardando preparação'}</Text></View>{cacheBusy&&<ActivityIndicator size="small" color="#ff334f"/>}</View><Text style={s.help}>O cache é preparado automaticamente pelo launcher.</Text>
  <Text style={s.section}>CLIENTE MYTHØS</Text><View style={s.client}><Text style={s.itemTitle}>MYTHØS SA-MP Mobile</Text><Text style={s.itemMeta}>{clientVersion?`Versão preparada: ${clientVersion}`:'Cliente 2.11 • ARM64/ARMv7'}</Text><TouchableOpacity style={s.secondary} onPress={installClient} disabled={clientBusy}>{clientBusy?<ActivityIndicator size="small" color="#ff334f"/>:<Text style={s.secondaryText}>BAIXAR / ATUALIZAR CLIENTE</Text>}</TouchableOpacity></View>
  <Text style={s.footer}>MYTHØS LAUNCHER • MYTHØS NETWORK • {SERVER.host}:{SERVER.port}</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050505'},content:{paddingBottom:35},header:{padding:20,alignItems:'center'},logo:{width:'100%',height:155},network:{color:'#888',fontSize:10,fontWeight:'900',letterSpacing:3},title:{color:'#fff',fontSize:31,fontWeight:'900',letterSpacing:2,marginTop:5},subtitle:{color:'#ff334f',fontSize:10,fontWeight:'800',letterSpacing:2,marginTop:4},status:{marginTop:14,flexDirection:'row',alignItems:'center',backgroundColor:'#111',borderRadius:20,paddingHorizontal:12,paddingVertical:7,borderWidth:1,borderColor:'#302025'},dot:{width:7,height:7,borderRadius:4,marginRight:7,backgroundColor:'#31d17c'},statusText:{color:'#ddd',fontSize:10,fontWeight:'900',letterSpacing:1},card:{margin:18,padding:21,borderRadius:21,backgroundColor:'#111',borderWidth:1,borderColor:'#4a2027'},kicker:{color:'#ff334f',fontSize:10,fontWeight:'900',letterSpacing:2},serverName:{color:'#fff',fontSize:25,fontWeight:'900',marginTop:8},meta:{color:'#818181',fontSize:11,marginTop:4},stats:{flexDirection:'row',justifyContent:'space-between',marginTop:22},number:{color:'#fff',fontSize:21,fontWeight:'900'},small:{color:'#777',fontSize:8,fontWeight:'900',marginTop:3},play:{marginTop:24,backgroundColor:'#ff334f',borderRadius:13,padding:16,alignItems:'center'},playText:{color:'#fff',fontSize:12,fontWeight:'900',letterSpacing:1},section:{marginHorizontal:22,marginTop:24,marginBottom:10,color:'#777',fontSize:10,fontWeight:'900',letterSpacing:2},cache:{marginHorizontal:18,padding:15,borderRadius:15,backgroundColor:'#0f0f0f',borderWidth:1,borderColor:'#282020',flexDirection:'row',alignItems:'center'},cacheIcon:{width:44,height:44,borderRadius:12,backgroundColor:'#ff334f',alignItems:'center',justifyContent:'center'},cacheIconText:{color:'#fff',fontWeight:'900',fontSize:19},cacheInfo:{flex:1,marginLeft:12},itemTitle:{color:'#fff',fontSize:13,fontWeight:'900'},itemMeta:{color:'#737373',fontSize:9,marginTop:4},help:{marginHorizontal:22,marginTop:8,color:'#555',fontSize:9,lineHeight:14},client:{marginHorizontal:18,padding:17,borderRadius:15,backgroundColor:'#0f0f0f',borderWidth:1,borderColor:'#222'},secondary:{marginTop:14,padding:12,borderRadius:10,backgroundColor:'#191010',alignItems:'center'},secondaryText:{color:'#ff5267',fontSize:9,fontWeight:'900'},footer:{textAlign:'center',color:'#555',fontSize:9,marginTop:30}});
